"""add api_keys

Revision ID: 114dbcb29256
Revises: 7c3594c899eb
Create Date: 2026-08-10 10:07:16.317764
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import gateway.persistence.types

revision: str = "114dbcb29256"
down_revision: str | None = "7c3594c899eb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_keys",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("client_id", sa.String(length=128), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("key_prefix", sa.String(length=16), nullable=False),
        sa.Column("scopes", gateway.persistence.types.JSONDocument(), nullable=False),
        sa.Column("control_overrides", gateway.persistence.types.JSONDocument(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("expires_at", gateway.persistence.types.UTCDateTime(), nullable=True),
        sa.Column("last_used_at", gateway.persistence.types.UTCDateTime(), nullable=True),
        sa.Column(
            "created_at",
            gateway.persistence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            gateway.persistence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_keys")),
        sa.UniqueConstraint("key_hash", name="uq_api_keys_key_hash"),
        sa.UniqueConstraint("key_hash", name=op.f("uq_api_keys_key_hash")),
    )
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.create_index("ix_api_keys_client_enabled", ["client_id", "enabled"], unique=False)
        batch_op.create_index(batch_op.f("ix_api_keys_client_id"), ["client_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_api_keys_enabled"), ["enabled"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_keys_enabled"))
        batch_op.drop_index(batch_op.f("ix_api_keys_client_id"))
        batch_op.drop_index("ix_api_keys_client_enabled")

    op.drop_table("api_keys")
    # ### end Alembic commands ###
