"""add model routing priors

Revision ID: 20adb9e31a13
Revises: 114dbcb29256
Create Date: 2026-08-10 12:59:00.010337
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20adb9e31a13"
down_revision: str | None = "114dbcb29256"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("models", schema=None) as batch_op:
        batch_op.add_column(sa.Column("latency_prior_ms", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("pass_rate_prior", sa.Float(), nullable=False))
        batch_op.add_column(sa.Column("failure_rate_prior", sa.Float(), nullable=False))
        batch_op.add_column(sa.Column("priors_source", sa.String(length=200), nullable=False))
        batch_op.create_check_constraint(
            batch_op.f("ck_models_failure_rate_prior_is_probability"),
            "failure_rate_prior >= 0 AND failure_rate_prior <= 1",
        )
        batch_op.create_check_constraint(
            batch_op.f("ck_models_latency_prior_positive"), "latency_prior_ms > 0"
        )
        batch_op.create_check_constraint(
            batch_op.f("ck_models_pass_rate_prior_is_probability"),
            "pass_rate_prior >= 0 AND pass_rate_prior <= 1",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("models", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("ck_models_pass_rate_prior_is_probability"), type_="check"
        )
        batch_op.drop_constraint(batch_op.f("ck_models_latency_prior_positive"), type_="check")
        batch_op.drop_constraint(
            batch_op.f("ck_models_failure_rate_prior_is_probability"), type_="check"
        )
        batch_op.drop_column("priors_source")
        batch_op.drop_column("failure_rate_prior")
        batch_op.drop_column("pass_rate_prior")
        batch_op.drop_column("latency_prior_ms")

    # ### end Alembic commands ###
