"""initial schema

Revision ID: 7c3594c899eb
Revises:
Create Date: 2026-08-09 18:50:33.132940
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import gateway.persistence.types

revision: str = "7c3594c899eb"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "budgets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scope", sa.String(length=200), nullable=False),
        sa.Column("window_kind", sa.String(length=32), nullable=False),
        sa.Column("window_start", gateway.persistence.types.UTCDateTime(), nullable=False),
        sa.Column("window_end", gateway.persistence.types.UTCDateTime(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("hard_limit", gateway.persistence.types.Money(), nullable=False),
        sa.Column("spent", gateway.persistence.types.Money(), nullable=False),
        sa.Column("reserved", gateway.persistence.types.Money(), nullable=False),
        sa.Column(
            "created_at",
            gateway.persistence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            gateway.persistence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "window_kind IN ('hourly', 'daily', 'monthly', 'total')",
            name=op.f("ck_budgets_window_kind_known"),
        ),
        sa.CheckConstraint("hard_limit >= 0", name=op.f("ck_budgets_hard_limit_non_negative")),
        sa.CheckConstraint("reserved >= 0", name=op.f("ck_budgets_reserved_non_negative")),
        sa.CheckConstraint("spent >= 0", name=op.f("ck_budgets_spent_non_negative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_budgets")),
        sa.UniqueConstraint("scope", "window_kind", "window_start", name="uq_budgets_scope_window"),
    )
    op.create_table(
        "models",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("provider_model_id", sa.String(length=200), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("data_handling_tier", sa.String(length=32), nullable=False),
        sa.Column("quality_tier", sa.String(length=32), nullable=False),
        sa.Column("capabilities", gateway.persistence.types.JSONDocument(), nullable=False),
        sa.Column("supported_endpoints", gateway.persistence.types.JSONDocument(), nullable=False),
        sa.Column("context_window_tokens", sa.Integer(), nullable=False),
        sa.Column("max_output_tokens", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            gateway.persistence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            gateway.persistence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "data_handling_tier IN ('public_only', 'standard', 'zdr')",
            name=op.f("ck_models_data_handling_tier_known"),
        ),
        sa.CheckConstraint(
            "quality_tier IN ('economy', 'standard', 'high', 'critical')",
            name=op.f("ck_models_quality_tier_known"),
        ),
        sa.CheckConstraint(
            "context_window_tokens > 0", name=op.f("ck_models_context_window_positive")
        ),
        sa.CheckConstraint("max_output_tokens > 0", name=op.f("ck_models_max_output_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_models")),
    )
    with op.batch_alter_table("models", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_models_data_handling_tier"), ["data_handling_tier"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_models_enabled"), ["enabled"], unique=False)
        batch_op.create_index(batch_op.f("ix_models_provider"), ["provider"], unique=False)

    op.create_table(
        "quota_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model_id", sa.String(length=128), nullable=True),
        sa.Column("window_kind", sa.String(length=32), nullable=False),
        sa.Column("observed_at", gateway.persistence.types.UTCDateTime(), nullable=False),
        sa.Column("limit_value", sa.Integer(), nullable=True),
        sa.Column("remaining", sa.Integer(), nullable=True),
        sa.Column("resets_at", gateway.persistence.types.UTCDateTime(), nullable=True),
        sa.Column(
            "created_at",
            gateway.persistence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "remaining IS NULL OR remaining >= 0",
            name=op.f("ck_quota_snapshots_remaining_non_negative"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quota_snapshots")),
    )
    with op.batch_alter_table("quota_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            "ix_quota_snapshots_latest",
            ["provider", "model_id", "window_kind", "observed_at"],
            unique=False,
        )

    op.create_table(
        "requests",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("client_id", sa.String(length=128), nullable=False),
        sa.Column("endpoint", sa.String(length=32), nullable=False),
        sa.Column("requested_model", sa.String(length=128), nullable=False),
        sa.Column(
            "normalized_controls_json", gateway.persistence.types.JSONDocument(), nullable=False
        ),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("terminal_reason", sa.String(length=128), nullable=True),
        sa.Column("deadline_at", gateway.persistence.types.UTCDateTime(), nullable=False),
        sa.Column("policy_id", sa.String(length=128), nullable=True),
        sa.Column("policy_version", sa.Integer(), nullable=True),
        sa.Column("registry_snapshot_at", gateway.persistence.types.UTCDateTime(), nullable=True),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("estimated_input_tokens", sa.Integer(), nullable=False),
        sa.Column("max_cost", gateway.persistence.types.Money(), nullable=False),
        sa.Column("cost_actual", gateway.persistence.types.Money(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            gateway.persistence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            gateway.persistence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "endpoint IN ('chat_completions', 'responses')", name=op.f("ck_requests_endpoint_known")
        ),
        sa.CheckConstraint(
            "state IN ('RECEIVED', 'AUTHENTICATING', 'NORMALIZING', 'CLASSIFYING', 'PLANNING', 'READY', 'RESERVING', 'INVOKING', 'RETRY_WAIT', 'VALIDATING', 'REPAIR_PLANNING', 'ESCALATION_PLANNING', 'SUCCEEDED', 'REJECTED', 'REJECTED_NO_ROUTE', 'REJECTED_BUDGET', 'FAILED', 'FAILED_PARTIAL', 'FAILED_EXHAUSTED', 'CANCELLED', 'EXPIRED')",
            name=op.f("ck_requests_state_known"),
        ),
        sa.CheckConstraint("cost_actual >= 0", name=op.f("ck_requests_cost_actual_non_negative")),
        sa.CheckConstraint(
            "estimated_input_tokens >= 0", name=op.f("ck_requests_input_tokens_non_negative")
        ),
        sa.CheckConstraint("max_cost >= 0", name=op.f("ck_requests_max_cost_non_negative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requests")),
    )
    with op.batch_alter_table("requests", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_requests_client_id"), ["client_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_requests_input_hash"), ["input_hash"], unique=False)
        batch_op.create_index(batch_op.f("ix_requests_state"), ["state"], unique=False)
        batch_op.create_index("ix_requests_state_created", ["state", "created_at"], unique=False)

    op.create_table(
        "routing_policies",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("policy_id", sa.String(length=128), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("task_class", sa.String(length=64), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("quality_floor", sa.String(length=32), nullable=False),
        sa.Column("max_generation_attempts", sa.Integer(), nullable=False),
        sa.Column("max_same_model_repairs", sa.Integer(), nullable=False),
        sa.Column("weights", gateway.persistence.types.JSONDocument(), nullable=False),
        sa.Column("validation_plan", gateway.persistence.types.JSONDocument(), nullable=False),
        sa.Column("priors_source", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            gateway.persistence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            gateway.persistence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quality_floor IN ('economy', 'standard', 'high', 'critical')",
            name=op.f("ck_routing_policies_quality_floor_known"),
        ),
        sa.CheckConstraint(
            "max_generation_attempts BETWEEN 1 AND 5",
            name=op.f("ck_routing_policies_generation_attempts_in_range"),
        ),
        sa.CheckConstraint(
            "max_same_model_repairs >= 0",
            name=op.f("ck_routing_policies_same_model_repairs_non_negative"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_routing_policies")),
        sa.UniqueConstraint("policy_id", "version", name="uq_routing_policies_policy_version"),
    )
    with op.batch_alter_table("routing_policies", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_routing_policies_active"), ["active"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_routing_policies_policy_id"), ["policy_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_routing_policies_task_class"), ["task_class"], unique=False
        )

    op.create_table(
        "budget_reservations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("request_id", sa.String(length=128), nullable=False),
        sa.Column("attempt_id", sa.String(length=128), nullable=True),
        sa.Column("budget_id", sa.Integer(), nullable=False),
        sa.Column("reserved_amount", gateway.persistence.types.Money(), nullable=False),
        sa.Column("settled_amount", gateway.persistence.types.Money(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("expires_at", gateway.persistence.types.UTCDateTime(), nullable=False),
        sa.Column("resolved_at", gateway.persistence.types.UTCDateTime(), nullable=True),
        sa.Column(
            "created_at",
            gateway.persistence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            gateway.persistence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'SETTLED', 'RELEASED', 'EXPIRED')",
            name=op.f("ck_budget_reservations_status_known"),
        ),
        sa.CheckConstraint(
            "reserved_amount >= 0", name=op.f("ck_budget_reservations_reserved_amount_non_negative")
        ),
        sa.CheckConstraint(
            "settled_amount IS NULL OR settled_amount >= 0",
            name=op.f("ck_budget_reservations_settled_amount_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["budget_id"],
            ["budgets.id"],
            name=op.f("fk_budget_reservations_budget_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["requests.id"],
            name=op.f("fk_budget_reservations_request_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_budget_reservations")),
        sa.UniqueConstraint("attempt_id", "budget_id", name="uq_reservations_attempt_budget"),
    )
    with op.batch_alter_table("budget_reservations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_budget_reservations_attempt_id"), ["attempt_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_budget_reservations_budget_id"), ["budget_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_budget_reservations_expires_at"), ["expires_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_budget_reservations_request_id"), ["request_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_budget_reservations_status"), ["status"], unique=False)

    op.create_table(
        "idempotency_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("client_id", sa.String(length=128), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("request_id", sa.String(length=128), nullable=True),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("response_ref", sa.Text(), nullable=True),
        sa.Column("expires_at", gateway.persistence.types.UTCDateTime(), nullable=False),
        sa.Column(
            "created_at",
            gateway.persistence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            gateway.persistence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state IN ('IN_PROGRESS', 'COMPLETED', 'FAILED')",
            name=op.f("ck_idempotency_records_idempotency_state_known"),
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["requests.id"],
            name=op.f("fk_idempotency_records_request_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_records")),
        sa.UniqueConstraint("client_id", "idempotency_key", name="uq_idempotency_client_key"),
    )
    with op.batch_alter_table("idempotency_records", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_idempotency_records_expires_at"), ["expires_at"], unique=False
        )

    op.create_table(
        "model_prices",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("model_id", sa.String(length=128), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("input_per_1k_tokens", gateway.persistence.types.Money(), nullable=False),
        sa.Column("output_per_1k_tokens", gateway.persistence.types.Money(), nullable=False),
        sa.Column("request_fee", gateway.persistence.types.Money(), nullable=False),
        sa.Column("effective_from", gateway.persistence.types.UTCDateTime(), nullable=False),
        sa.Column("effective_to", gateway.persistence.types.UTCDateTime(), nullable=True),
        sa.Column("source", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            gateway.persistence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            gateway.persistence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to > effective_from",
            name=op.f("ck_model_prices_price_window_ordered"),
        ),
        sa.CheckConstraint(
            "input_per_1k_tokens >= 0", name=op.f("ck_model_prices_input_price_non_negative")
        ),
        sa.CheckConstraint(
            "output_per_1k_tokens >= 0", name=op.f("ck_model_prices_output_price_non_negative")
        ),
        sa.CheckConstraint(
            "request_fee >= 0", name=op.f("ck_model_prices_request_fee_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["model_id"], ["models.id"], name=op.f("fk_model_prices_model_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_prices")),
        sa.UniqueConstraint("model_id", "effective_from", name="uq_model_prices_model_from"),
    )
    with op.batch_alter_table("model_prices", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_model_prices_model_id"), ["model_id"], unique=False)

    op.create_table(
        "attempts",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("request_id", sa.String(length=128), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("model_id", sa.String(length=128), nullable=False),
        sa.Column("route_rank", sa.Integer(), nullable=False),
        sa.Column("attempt_kind", sa.String(length=32), nullable=False),
        sa.Column("retry_of_attempt_id", sa.String(length=128), nullable=True),
        sa.Column("reservation_id", sa.Integer(), nullable=True),
        sa.Column("emitted_output", sa.Boolean(), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("finish_reason", sa.String(length=32), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_estimated", gateway.persistence.types.Money(), nullable=False),
        sa.Column("cost_actual", gateway.persistence.types.Money(), nullable=True),
        sa.Column("started_at", gateway.persistence.types.UTCDateTime(), nullable=True),
        sa.Column("finished_at", gateway.persistence.types.UTCDateTime(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("output_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            gateway.persistence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            gateway.persistence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "attempt_kind IN ('GENERATION', 'REPAIR', 'ESCALATION', 'VALIDATOR')",
            name=op.f("ck_attempts_attempt_kind_known"),
        ),
        sa.CheckConstraint(
            "outcome IS NULL OR outcome IN ('SUCCESS', 'TIMEOUT', 'RATE_LIMITED', 'PROVIDER_ERROR', 'AUTH_ERROR', 'CAPABILITY_REJECTED', 'CONTEXT_REJECTED', 'INVALID_RESPONSE', 'CANCELLED', 'PARTIAL')",
            name=op.f("ck_attempts_outcome_known"),
        ),
        sa.CheckConstraint(
            "cost_actual IS NULL OR cost_actual >= 0",
            name=op.f("ck_attempts_attempt_cost_actual_non_negative"),
        ),
        sa.CheckConstraint(
            "cost_estimated >= 0", name=op.f("ck_attempts_attempt_cost_estimated_non_negative")
        ),
        sa.CheckConstraint("route_rank >= 0", name=op.f("ck_attempts_route_rank_non_negative")),
        sa.CheckConstraint("sequence >= 1", name=op.f("ck_attempts_sequence_positive")),
        sa.ForeignKeyConstraint(
            ["request_id"], ["requests.id"], name=op.f("fk_attempts_request_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["budget_reservations.id"],
            name=op.f("fk_attempts_reservation_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["retry_of_attempt_id"],
            ["attempts.id"],
            name=op.f("fk_attempts_retry_of_attempt_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attempts")),
        sa.UniqueConstraint("request_id", "sequence", name="uq_attempts_request_sequence"),
    )
    with op.batch_alter_table("attempts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_attempts_model_id"), ["model_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_attempts_request_id"), ["request_id"], unique=False)

    op.create_table(
        "validations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("request_id", sa.String(length=128), nullable=False),
        sa.Column("attempt_id", sa.String(length=128), nullable=False),
        sa.Column("validator_name", sa.String(length=64), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("result", sa.String(length=32), nullable=False),
        sa.Column("aggregate_effect", sa.Boolean(), nullable=False),
        sa.Column("validator_attempt_id", sa.String(length=128), nullable=True),
        sa.Column("detail_codes", gateway.persistence.types.JSONDocument(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            gateway.persistence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            gateway.persistence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "result IN ('PASS', 'INDETERMINATE', 'FAIL_REPAIRABLE', 'FAIL_QUALITY', 'FAIL_CAPABILITY', 'FAIL_GROUNDING')",
            name=op.f("ck_validations_result_known"),
        ),
        sa.CheckConstraint(
            "sequence >= 1", name=op.f("ck_validations_validation_sequence_positive")
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["attempts.id"],
            name=op.f("fk_validations_attempt_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["requests.id"],
            name=op.f("fk_validations_request_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["validator_attempt_id"],
            ["attempts.id"],
            name=op.f("fk_validations_validator_attempt_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_validations")),
        sa.UniqueConstraint(
            "attempt_id", "validator_name", "sequence", name="uq_validations_attempt_validator"
        ),
    )
    with op.batch_alter_table("validations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_validations_attempt_id"), ["attempt_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_validations_request_id"), ["request_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("validations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_validations_request_id"))
        batch_op.drop_index(batch_op.f("ix_validations_attempt_id"))

    op.drop_table("validations")
    with op.batch_alter_table("attempts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attempts_request_id"))
        batch_op.drop_index(batch_op.f("ix_attempts_model_id"))

    op.drop_table("attempts")
    with op.batch_alter_table("model_prices", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_model_prices_model_id"))

    op.drop_table("model_prices")
    with op.batch_alter_table("idempotency_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_idempotency_records_expires_at"))

    op.drop_table("idempotency_records")
    with op.batch_alter_table("budget_reservations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_budget_reservations_status"))
        batch_op.drop_index(batch_op.f("ix_budget_reservations_request_id"))
        batch_op.drop_index(batch_op.f("ix_budget_reservations_expires_at"))
        batch_op.drop_index(batch_op.f("ix_budget_reservations_budget_id"))
        batch_op.drop_index(batch_op.f("ix_budget_reservations_attempt_id"))

    op.drop_table("budget_reservations")
    with op.batch_alter_table("routing_policies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_routing_policies_task_class"))
        batch_op.drop_index(batch_op.f("ix_routing_policies_policy_id"))
        batch_op.drop_index(batch_op.f("ix_routing_policies_active"))

    op.drop_table("routing_policies")
    with op.batch_alter_table("requests", schema=None) as batch_op:
        batch_op.drop_index("ix_requests_state_created")
        batch_op.drop_index(batch_op.f("ix_requests_state"))
        batch_op.drop_index(batch_op.f("ix_requests_input_hash"))
        batch_op.drop_index(batch_op.f("ix_requests_client_id"))

    op.drop_table("requests")
    with op.batch_alter_table("quota_snapshots", schema=None) as batch_op:
        batch_op.drop_index("ix_quota_snapshots_latest")

    op.drop_table("quota_snapshots")
    with op.batch_alter_table("models", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_models_provider"))
        batch_op.drop_index(batch_op.f("ix_models_enabled"))
        batch_op.drop_index(batch_op.f("ix_models_data_handling_tier"))

    op.drop_table("models")
    op.drop_table("budgets")
    # ### end Alembic commands ###
